In [29]:
marks= [78,84,62]
avg=sum(marks)/len(marks)
print(avg)

74.66666666666667


In [30]:
def calculate_average(marks):
  return sum(marks) / len(marks)

student_marks = [78,84,62]
average = calculate_average(student_marks)
print(average)

74.66666666666667


In [31]:
import numpy as np
marks= np.array([78,84,62])
print (marks +10)

[88 94 72]


In [32]:
import numpy as np
marks= np.array([78,84,62])
print (marks +10)

[88 94 72]


In [33]:
import numpy as np

arr= np.array([10,20,30,40])
print (arr)
print(arr.shape)


matrix=np.array([
    [10,20,30],
    [40,50,60]
])
print (matrix)
print(matrix.shape)

[10 20 30 40]
(4,)
[[10 20 30]
 [40 50 60]]
(2, 3)


In [34]:
#indexing and slicing
grid = np.array([
    [11, 12, 13, 14, 15],
    [21, 22, 23, 24, 25],
    [31, 32, 33, 34, 35],
    [41, 42, 43, 44, 45],
    [51, 52, 53, 54, 55]

])


print(grid[0,0])
print(grid[2,3])
print(grid[1,4])
print(grid[1,4])
print(grid[0])
print(grid[:,0])
print(grid[3,3])
grid[1:4,1:4]

11
34
25
25
[11 12 13 14 15]
[11 21 31 41 51]
44


array([[22, 23, 24],
       [32, 33, 34],
       [42, 43, 44]])

In [35]:
marks = np.array([78,91,55,72,40,88])

print(marks>70)

high_scorers = marks[marks>70]
print(high_scorers)


print(marks[(marks >= 60) & (marks <= 70)])
print(marks[(marks < 60) | (marks > 70)])

[ True  True False  True False  True]
[78 91 72 88]
[]
[78 91 55 72 40 88]


In [36]:
marks = np.array([78,91,55,72,40,88])

print(marks.mean())
print(marks.min())
print(marks.max())
print(marks.sum())


70.66666666666667
40
91
424


In [37]:
import pandas as pd

df = pd.read_csv("session4_dummy_students_data.csv")
print(df)


FileNotFoundError: [Errno 2] No such file or directory: 'session4_dummy_students_data.csv'

In [ ]:
print(df.head())
print(df.columns)
print(df.shape)
print(df.info())


In [ ]:
#convert math score column to numpy
math_scores =df["math"].to_numpy()
print(math_scores)
print(type(math_scores))
print(math_scores.mean())

In [ ]:
#calculate avg accross all subjects
df["average"] = df[["math", "science", "english"]].mean(axis=1)
print(df[["name", "math", "science", "english", "average"]])



In [ ]:
# 3 filters
#1st filter top students whose avg is greater than 85
#2nd low attenadance, attendance less than 75
#filter students from mathura

top_students =df[df["average"] >=85]
print(top_students[["name","average"]])


low_attendance = df[df["attendance_percent"] < 75]
print(low_attendance[["name", "attendance_percent"]])

mumbai_students = df[df["city"] == "Mumbai"]
print(mumbai_students[["name", "city", "average"]])
