In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

students = pd.DataFrame({
    "name": ["Aarav", "Riya", "Kabir", "Meera", "Dev", "Sara"],
    "study_hours": [6, 3, 8, 2, 5, 7],
    "attendance": [85, 70, 90, 60, 78, 92],
    "previous_marks": [78, 55, 88, 35, 65, 84],
    "final_marks": [82, 58, 91, 40, 70, 88]
})


In [ ]:
feature_columns = ["study_hours", "attendance", "previous_marks"]
student_vectors = students[feature_columns].values
print(student_vectors)

[[ 6 85 78]
 [ 3 70 55]
 [ 8 90 88]
 [ 2 60 35]
 [ 5 78 65]
 [ 7 92 84]]


In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

similarity_matrix = cosine_similarity(student_vectors)


similarity_df =pd.DataFrame(
    similarity_matrix,
    index=students["name"],
    columns=students["name"]
)

similarity_df

name,Aarav,Riya,Kabir,Meera,Dev,Sara
name,,,,,,
Aarav,1.000000,0.996913,0.999434,0.976875,0.998860,0.999988
Riya,0.996913,1.000000,0.993724,0.990505,0.999467,0.997017
Kabir,0.999434,0.993724,1.000000,0.969344,0.996756,0.999391
Meera,0.976875,0.990505,0.969344,1.000000,0.985958,0.977304
Dev,0.998860,0.999467,0.996756,0.985958,1.000000,0.998956
Sara,0.999988,0.997017,0.999391,0.977304,0.998956,1.000000


In [ ]:
from matplotlib import MatplotlibDeprecationWarning
#embeddings

an embedding is a vector that represents MatplotlibDeprecationWarning
wordsm imagesm products, users, sentences converted into embeddings

In [ ]:
#In RAG systems we convert documents into embeddings


In [ ]:
#Tokenisation using OpenAi tokeniser


In [ ]:
#Tokns can be full words, parts of words, spaces, punctuaion or special chunks
#Text --tokens--token id--embediings- model

In [ ]:
sentence = "The movie was not good"

tokens= sentence.lower().split()
print(tokens)

['the', 'movie', 'was', 'not', 'good']


In [ ]:
vocab = {
    "the": 1,
    "movie": 2,
    "was": 3,
    "not": 4,
    "good": 5
}
token_ids = [vocab[word] for word in tokens]

print(token_ids)


[1, 2, 3, 4, 5]


In [ ]:
Dog bites man
Man bites dog


#The movie was good
#the movie was not good
the movie was good not



#ex 3
I only said she stole my phone
Only I said she stole my phone
I said only she tole my phone
I said she only stole my phone


not bad bad not
can i go

i can go

In [ ]:
sentences=[
    "dog bites man",
    "man bites dog",
    "the movie was good",
    "the movie was not good"
]

for sentence in sentences:
  print(sentence,"->", sentence.split())

dog bites man -> ['dog', 'bites', 'man']
man bites dog -> ['man', 'bites', 'dog']
the movie was good -> ['the', 'movie', 'was', 'good']
the movie was not good -> ['the', 'movie', 'was', 'not', 'good']


In [ ]:
positive_words = ["good", "great", "amazing", "excellent", "love"]
negative_words = ["bad", "terrible", "poor", "hate", "boring"]

def simple_sentiment(sentence):
    words = sentence.lower().replace(".", "").split()

    score = 0

    for word in words:
        if word in positive_words:
            score += 1
        elif word in negative_words:
            score -= 1

    if score > 0:
        return "Positive"
    elif score < 0:
        return "Negative"
    else:
        return "Neutral"

print(simple_sentiment("The movie was good"))
print(simple_sentiment("The movie was bad"))
print(simple_sentiment("The movie was not good"))


Positive
Negative
Positive


In [ ]:
def better_sentiment_with_not(sentence):
    words = sentence.lower().replace(".", "").split()

    score = 0

    for i, word in enumerate(words):
        previous_word = words[i - 1] if i > 0 else ""

        if word in positive_words:
            if previous_word == "not":
                score -= 1
            else:
                score += 1

        elif word in negative_words:
            if previous_word == "not":
                score += 1
            else:
                score -= 1

    if score > 0:
        return "Positive"
    elif score < 0:
        return "Negative"
    else:
        return "Neutral"

print(better_sentiment_with_not("The movie was good"))
print(better_sentiment_with_not("The movie was not good"))
print(better_sentiment_with_not("The movie was not bad"))


Positive
Negative
Positive
